<?php
$this->title = $this->report->news_title . '：回報新聞錯誤：';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h2>回報資訊: <?= $this->escape($this->report->news_title) ?></h2>
新聞連結：<a href="<?= $this->escape($this->report->news_link) ?>" target="_blank" rel="nofollow"><?= $this->escape($this->report->news_link) ?></a><br>
新聞標題：<?= $this->escape($this->report->news_title) ?><br>
打臉證據：<a href="<?= $this->escape($this->report->report_link) ?>" target="_blank" rel="nofollow"><?= $this->escape($this->report->report_link) ?></a><br>
打臉原因：<?= $this->escape($this->report->report_title) ?><br>
<hr>
<h2>編修記錄</h2>
<table class="table">
    <thead>
        <tr>
            <td>時間</td>
            <td>修改人</td>
            <td>舊值</td>
            <td>新值</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (ReportChangeLog::search(array('report_id' => $this->report->id)) as $change_log) { ?>
    <tr>
        <td><?= date('c', $change_log->updated_at) ?></td>
        <td>
            <?= $this->escape($change_log->updated_by) ?>
            IP: <?= long2ip($change_log->updated_from) ?>
        </td>
        <td><?= $this->partial('index/log_show.phtml', array('value' => $change_log->old_values)) ?></td>
        <td><?= $this->partial('index/log_show.phtml', array('value' => $change_log->new_values)) ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?= $this->partial('/common/footer.phtml', $this) ?>
