DROP TABLE IF EXISTS prove_links;
DROP TABLE IF EXISTS news_links;
DROP TABLE IF EXISTS news;

CREATE TABLE news (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  description MEDIUMTEXT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE news_links (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  news_id INT,
  url TEXT NOT NULL,
  INDEX (url(128)),
  INDEX (news_id),
  FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE prove_links (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  news_id INT,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  INDEX (news_id),
  FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

